name: Pack & Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pack
        run: choco pack
        
      - name: Publish
        shell: powershell
        env:
          CHOCO_SECRET: ${{ secrets.CHOCO_SECRET }}
        run: choco push .\mandelbulber2*.nupkg -s https://push.chocolatey.org/ -k "$CHOCO_SECRET" 
