name: Pack & Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pack
        run: choco pack
        
      - name: Set API Key
        shell: powershell
        env:
            CHOCO_SECRET: ${{ secrets.CHOCO_SECRET }}
        run: choco apikey --api-key=$CHOCO_SECRET -source https://push.chocolatey.org/
        
      - name: Publish
        shell: powershell
        run: choco push .\mandelbulber2*.nupkg -s https://push.chocolatey.org/
